### ISSUE TITLE
Libre.fm will not create a token

### ISSUE THREAD

**Issue by prpl4** [digitalheir/lastfm-to-librefm-exporter#5]
On the inline webpage section where it's suppoed to load it, it just shows an error webpage on most browsers (firefox/chrome) and if proceeding to site, you get 

' Invalid Method - No method with that name in this package '

Any help?

**Comment by WhereAreWeSeeing** [comment]
https://libre.fm/2.0/ I get this page
![image](https://user-images.githubusercontent.com/56249225/146837463-a56f5abc-9d28-466d-a23d-6f83160e926e.png)
